from PyQt5 import QtCore, QtGui, QtWidgets

class Login(object):
    def setupUi(self, LoginForm):
        LoginForm.setWindowTitle("RSAS 批量下任务1.0")
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(319, 103)
        LoginForm.setMinimumSize(QtCore.QSize(319, 103))
        LoginForm.setMaximumSize(QtCore.QSize(319, 103))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        LoginForm.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(LoginForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 54))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.username_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.username_label.setObjectName("username_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.username_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.username_lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)

        self.passwd_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwd_label.setObjectName("passwd_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwd_label)
        self.passwd_lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwd_lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.passwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_lineEdit.setObjectName("passwd_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwd_lineEdit)

        self.login_Button = QtWidgets.QPushButton(LoginForm)
        self.login_Button.setGeometry(QtCore.QRect(10, 70, 301, 23))
        self.login_Button.setObjectName("login_Button")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "LoginForm"))
        self.username_label.setText(_translate("LoginForm", "用户名："))
        self.passwd_label.setText(_translate("LoginForm", "密  码："))
        self.login_Button.setText(_translate("LoginForm", "登陆"))

class Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName("Admin")
        Admin.resize(351, 200)
        Admin.setMinimumSize(QtCore.QSize(351, 200))
        Admin.setMaximumSize(QtCore.QSize(351, 200))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        Admin.setFont(font)
        Admin.setMouseTracking(False)
        Admin.setTabletTracking(False)
        Admin.setFocusPolicy(QtCore.Qt.NoFocus)
        Admin.setAcceptDrops(False)
        Admin.setToolTipDuration(-1)
        Admin.setAutoFillBackground(False)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Admin)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 311, 51))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.SetPost_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.SetPost_label.setObjectName("SetPost_label")
        self.horizontalLayout_3.addWidget(self.SetPost_label)
        self.AllPort_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.AllPort_checkBox.setChecked(True)
        self.AllPort_checkBox.setTristate(False)
        self.AllPort_checkBox.setObjectName("AllPort_checkBox")
        self.horizontalLayout_3.addWidget(self.AllPort_checkBox)
        self.DefaultPort_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.DefaultPort_checkBox.setObjectName("DefaultPort_checkBox")
        self.horizontalLayout_3.addWidget(self.DefaultPort_checkBox)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.survival_label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.survival_label.setObjectName("survival_label")
        self.horizontalLayout_4.addWidget(self.survival_label)
        self.survival_cancel_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.survival_cancel_checkBox.setObjectName("survival_cancel_checkBox")
        self.horizontalLayout_4.addWidget(self.survival_cancel_checkBox)
        self.survival_Definition_checkBox = QtWidgets.QCheckBox(self.formLayoutWidget_2)
        self.survival_Definition_checkBox.setChecked(False)
        self.survival_Definition_checkBox.setObjectName("survival_Definition_checkBox")
        self.horizontalLayout_4.addWidget(self.survival_Definition_checkBox)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.formLayoutWidget = QtWidgets.QWidget(Admin)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 70, 311, 22))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Scan_Template_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Scan_Template_label.setObjectName("Scan_Template_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Scan_Template_label)
        self.TemplateList_comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.TemplateList_comboBox.setObjectName("TemplateList_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TemplateList_comboBox)
        self.Status_label = QtWidgets.QLabel(Admin)
        self.Status_label.setGeometry(QtCore.QRect(20, 170, 321, 22))
        self.Status_label.setObjectName("Status_label")
        self.start_Button = QtWidgets.QPushButton(Admin)
        self.start_Button.setGeometry(QtCore.QRect(260, 110, 71, 23))
        self.start_Button.setObjectName("start_Button")
        self.Working_label = QtWidgets.QLabel(Admin)
        self.Working_label.setGeometry(QtCore.QRect(20, 110, 241, 22))
        self.Working_label.setObjectName("Working_label")

        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)

    def retranslateUi(self, Admin):
        _translate = QtCore.QCoreApplication.translate
        Admin.setWindowTitle(_translate("Admin", "Form"))
        self.SetPost_label.setText(_translate("Admin", "端口扫描配置："))
        self.AllPort_checkBox.setText(_translate("Admin", "全部端口扫描"))
        self.DefaultPort_checkBox.setText(_translate("Admin", "默认端口扫描"))
        self.survival_label.setText(_translate("Admin", "存活探测配置："))
        self.survival_cancel_checkBox.setText(_translate("Admin", "取消存活探测"))
        self.survival_Definition_checkBox.setText(_translate("Admin", "定义探测端口"))
        self.Scan_Template_label.setText(_translate("Admin", "扫描模板配置： "))
        self.Status_label.setText(_translate("Admin", "状态：当前有 个任务正在进行, 个任务等待扫描"))
        self.start_Button.setText(_translate("Admin", "开始下任务"))
        self.Working_label.setText(_translate("Admin", ""))
